# Generated by Django 4.2.2 on 2024-05-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_cancel_publish_product', 'Может отменять публикацию продукта'), ('can_change_product_description', 'Может менять описание продукта'), ('can_change_product_category', 'Может менять категорию продукта')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='publish_status',
            field=models.CharField(choices=[('not_published', 'Не опубликовано'), ('published', 'Опубликовано')], default='not_published', max_length=15, verbose_name='Статус публикации'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Введите описание продукта', verbose_name='Описание'),
        ),
    ]
